spring:
  datasource:
    username: postgres
    password: cHJvbWV0aGV1cw==
    url: jdbc:postgresql://localhost:5434/java_spring_grpc
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
