version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: java_spring_grpc
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cHJvbWV0aGV1cw==}
    ports:
      - "5434:5432"
